#%RAML 1.0 Library

usage: Type definitions for Connected Application Settings

uses:
  primitives: ./primitives.raml

types:
  ConnectedApplicationUpdate:
    additionalProperties: false
    properties:
      client_id?:
        type: StringField
      client_name?:
        type: StringField
      client_secret?:
        type: StringField

      owner_org_id?:
        type: StringField
      owner_user_id?:
        type: StringField
        description: |
          The ID of the user that owns the application. Sending a different ID transfers the application to a new owner.
          Only Organization Administrators may own an application.
          Ownerless Connected Apps cannot be given owners.
          Owned Connected Apps cannot be made ownerless.

      enabled?:
        type: boolean
      audience?:
        enum:
          - everyone
          - internal

      client_uri?:
        type: StringField
      policy_uri?:
        type: StringField
      tos_uri?:
        type: StringField

      public_keys?:
        type: array
        items:
          type: string
          minLength: 1
          maxLength: 4096

      grant_types?:
        type: array
        items:
          type: string
          enum:
            - implicit
            - authorization_code
            - refresh_token
            - client_credentials
            - password
            - urn:ietf:params:oauth:grant-type:jwt-bearer
        minItems: 1

      redirect_uris?:
        type: array
        items:
          type: string
          minLength: 1

      scopes?:
        type: array
        items:
          type: string
          minLength: 1

  ConnectedApplicationCreate:
    type: ConnectedApplicationUpdate
    properties:
      redirect_uris:
        type: array
        required: true
        items:
          type: string
          minLength: 1

      owner_org_id?:
        type: StringField
        description: |
          If provided, the App will be created in the target organization. Otherwise, it will default to the caller's organization.
          Should only be provided if creating an Ownerless Connected App.
      owner_user_id?:
        type: StringField
        description: |
          Send owner_user_id: null to create an Ownerless Connected App. Otherwise, it will default to the caller's ID.

  StringField:
    type: string
    minLength: 1
    maxLength: 255


  StringFieldArray:
    type: array
    items:
      type: StringField

  PublicConnectedApplication:
    additionalProperties: false
    properties:
      client_id:
        type: StringField
      client_name:
        type: StringField
      owner_org_id:
        type: StringField
      client_uri:
        type: StringField | nil
      policy_uri:
        type: StringField | nil
      tos_uri:
        type: StringField | nil

  ConnectedApplication:
    additionalProperties: false
    properties:
      client_id:
        type: StringField
      client_name:
        type: StringField
      client_secret:
        type: StringField

      owner_org_id:
        type: StringField

      enabled:
        type: boolean
      audience:
        enum:
          - everyone
          - internal

      client_uri:
        type: StringField | nil
      policy_uri:
        type: StringField | nil
      tos_uri:
        type: StringField | nil

      public_keys:
        type: array
        items:
          type: string
          minLength: 1
          maxLength: 4096

      grant_types:
        type: array
        items:
          type: string
          enum:
            - implicit
            - authorization_code
            - refresh_token
            - client_credentials
            - urn:ietf:params:oauth:grant-type:jwt-bearer
        minItems: 1

      redirect_uris:
        type: array
        items:
          type: StringField
          minLength: 1

      scopes:
        type: array
        items:
          type: StringField
          minLength: 1

      usage:
        type: object
        required: false
        additionalProperties: false
        properties:
          internal:
            type: number
            description: The number of users within the App's organization that have authorized it
          external:
            type: number
            description: The number of users outside the App's organization that have authorized it


  ConnectedApplicationSettings:
    properties:
      whitelist_enabled?:
        type: boolean
        description: |
          Deprecated. Use allowlist_enabled instead. When both properties are being set, allowlist_enabled is observed.
          If true, only applications on the Organization's allowlist may ask for consent/receive tokens.
          If false, any application can ask for consent/receive tokens.
      allowlist_enabled?:
        type: boolean
        description: |
          If true, only applications on the Organization's allowlist may ask for consent/receive tokens.
          If false, any application can ask for consent/receive tokens.
      applications_enabled:
        enum:
         - none
         - partial
         - all
        description: |
          If all, clients may access resouces in the Organization via any grant type.
          If none, clients may not access the Organization - this disables Connected Applications.
          If partial, clients may access resources in the Organization ony using grant_types in the grant_types_allowed list
      grant_types_allowed:
        type: string[]
        description: The list of all grant types the Organization allows clients to use
      whitelist_internal_applications?:
        type: boolean
        description: |
          Deprecated. Use allowlist_internal_applications instead. When both properties are being set,
          allowlist_internal_applications is observed.
          If true, all internal applications are auto-approved to be part of the allowlist.
          If false, internal applications must be added to the allowlist like any other app.
      allowlist_internal_applications?:
        type: boolean
        description: |
          If true, all internal applications are auto-approved to be part of the allowlist.
          If false, internal applications must be added to the allowlist like any other app.

  ConnectedApplicationSettingsWhitelistEntry:
     properties:
       client_id:
         type: string
         description: The ID of the client that is allowlisted
       authorized_scopes?:
         type: array
         items:
           type: string
         description: |
           The scopes the allowlisted client may request.
           If not provided, it defaults to the full set of scopes the client is registered to request.

  ConnectedApplicationSettingsAllowlistEntry:
     properties:
       client_id:
         type: string
         description: The ID of the client that is allowlisted
       authorized_scopes?:
         type: array
         items:
           type: string
         description: |
           The scopes the allowlisted client may request.
           If not provided, it defaults to the full set of scopes the client is registered to request.

  ConnectedApplicationSettingsWhitelist:
    type: array
    items:
      type: ConnectedApplicationSettingsWhitelistEntry

  ConnectedApplicationSettingsAllowlist:
      type: array
      items:
        type: ConnectedApplicationSettingsAllowlistEntry

  ConnectedApplicationSettingsUpdate:
    type: ConnectedApplicationSettings
    properties:
      import_existing_authorizations?:
        type: boolean
        description: If true, add all existing client authorizations to the allowlist with their registered scopes
      whitelist?:
        type: ConnectedApplicationSettingsWhitelistEntry[]
        description: A set of entries to upsert into to the allowlist.

  ConnectedApplicationAdminSearch:
    minProperties: 1
    properties:
      owner_org_id?:
         type: StringField
         description: Only return Connected Applications belonging to that Organization
      client_id?:
         type: StringField | StringFieldArray
         description: Only return Connected Applications with a matching client_id
