#%RAML 1.0 Library

usage: Type definitions for roles

annotationTypes:
  deprecated: string

uses:
  primitives: ./primitives.raml

types:
  ContextParams:
    type: object
    minProperties: 0
    maxProperties: 7
    properties:
      //:
        required: false
        type: string
        minLength: 1
        maxLength: 255

  RoleGroupApiResponse:
    additionalProperties: false
    properties:
      data:
        type: array
        items: RoleGroup
      total:
        type: integer

  RoleGroup:
    type: object
    properties:
      role_group_id: primitives.uuid
      name:
        type: string
        minLength: 1
        maxLength: 255
      description:
        type: string
        minLength: 1
        maxLength: 255
      org_id: primitives.uuid
      editable: boolean
      user_count: integer
      external_names: RoleGroupExternalName
      created_at: datetime
      updated_at: datetime
      assignments?: array

  RoleGroupUpdate:
    additionalProperties: false
    properties:
      role_group_id?: primitives.uuid
      name?:
        type: string
        minLength: 1
        maxLength: 255
      description?:
        type: string
        minLength: 1
        maxLength: 255
      external_names?: RoleGroupExternalName

  RoleGroupExternalName:
    type: array
    items: string | RoleGroupExternalMapping

  RoleGroupExternalMapping:
    additionalProperties: false
    properties:
      external_group_name:
        type: string
        minLength: 1
        maxLength: 255
      provider_id:
        type: primitives.uuid


  # I had to create this wrapper otherwise Osprey complains with all of these approach
  # that it cannot find the type: RoleAssignment in the apiV1.raml
  # ---
  # type: RoleAssignment[]
  # ---
  # type: array
  # items: RoleAssignment
  # ---
  # type: array
  # items:
  #   type: RoleAssignment
  RoleAssignmentCollectionRequest:
    type: RoleAssignment[]

  RoleAssignment:
    additionalProperties: false
    type: object
    properties:
      role_id:
        description: the id of the role
        type: primitives.IdString
      context_params:
        type: ContextParams

  RoleAssignmentDetailed:
    type: RoleAssignment
    additionalProperties: false
    properties:
      name:
        description: name of the role
        type: string
        minLength: 1
        maxLength: 255

  RoleAssignmentDetailedWithDate:
    type: RoleAssignmentDetailed
    additionalProperties: false
    properties:
      created_at:
        description: Time at which the role was assigned
        type: datetime

  RoleSearchExpression:
    additionalProperties: false
    properties:
      name:
        description: defines this expression as being a search expression
        enum: [ expression ]
      operator:
        description: the operation to perform on the operands
        enum: [ AND, OR ]
      operands:
        description: the values to search and match with
        type: array
        minItems: 1
        maxItems: 5
        items:
          additionalProperties: false
          properties:
            role_id?:
              description: the id of the role
              type: primitives.IdString
            context_params:
              description: context parameter conditions to match role assignments
              type: ContextParams
            match_type:
              description: |
                How to match the role.
                Exact matching means that the role assignment must have exactly the supplied context_params (no more and no less).
                Partial matching means that the role assignment must contain at least the supplied context_params (but may also have more).
              enum: [ exact, partial ]

  PaginationExpression:
    additionalProperties: false
    properties:
      name:
        description: defines this expression as being a pagination expression
        enum: [ pagination ]
      limit:
        description: return a maximum of this many results
        type: integer
      offset:
        description: return results starting at this position
        type: integer

  SortingExpression:
    additionalProperties: false
    properties:
      name:
        description: defines this expression as being a sorting expression
        enum: [ sort ]
      field:
        description: sort by this field
        type: string
      order?:
        description: order the results in either ascending (ASC) or descending (DESC) order
        enum: [ ASC, DESC ]
        default: DESC

  RoleExpressionSearchCollection:
    type: array
    minItems: 1
    maxItems: 3
    uniqueItems: true
    items:
      type: RoleSearchExpression | PaginationExpression | SortingExpression

  ConditionalAssignments:
    type: object
    additionalProperties: false
    properties:
      organizations:
        description: Organization and Environment context hierarchies
        type: array
        items: ContextHierarchyBusinessGroup
      products:
        description: Product data
        type: array
        items: Product

  ContextHierarchyBusinessGroup:
    type: object
    additionalProperties: false
    properties:
      id:
        description: the id of the business group
        type: primitives.IdString
      name:
        description: the name of the business group
        type: string
      isRoot:
        description: whether the business group is the root organization
        type: boolean
      isMaster:
        (deprecated): prefer isRoot
        description: whether or not the business group is the root organization
        type: boolean
      environments:
        description: the environments under the organization
        type: array
        items: ContextHierarchyEnvironment

  ContextHierarchyEnvironment:
    type: object
    additionalProperties: false
    properties:
      id:
        description: the id of the environment
        type: primitives.IdString
      name:
        description: the name of the environment
        type: string
      type:
        description: the type of the environment
        enum: [design, sandbox, production]

  Product:
    type: object
    additionalProperties: false
    properties:
      product_id:
        description: the id of the product
        type: string
      label:
        description: human-friendly name for the product
        type: string
      permissions:
        description: the permisions associated with the product
        type: array
        items: Permission

  Permission:
    type: object
    additionalProperties: false
    properties:
      role_id:
        description: the id of the role linked to this permission
        type: primitives.IdString
      scope?:
        description: the scope linked to this permission
        type: primitives.IdString
      displayName:
        description: human-friendly name for the permission
        type: primitives.IdString
      description:
        description: summary of what the permission does
        type: primitives.IdString
      contextKeys:
        description: the required context keys the permission must be assigned with
        type: array
        items:
          enum: [ org, envId ]
      conditions:
        description: any special conditions that must be met for the permission to be allowed
        type: array
        items:
          enum: [ noSubOrganizations, noDesignEnvironments ]
